version: 0.0
environment_variables:
    plaintext:
        "S3_BUCKET": "cryp-unittest-reports"
        "PROJECT_NAME": "cryp-services"
containers:
    LambdaFunctions:
        phases:
            install:
                commands:
                    - echo Installing Dependency...
                    - npm install -g next
                    - yarn
            pre_build:
                commands:
            during_build:
                commands:
                    - chmod +x serverless_deploy_dev.sh
                    - serverless_deploy_dev.sh
