version: 0.0
environment_variables:
    plaintext:
        "S3_BUCKET": "cryp-unittest-reports"
        "PROJECT_NAME": "cryp-services"
containers:
    LambdaFunctions:
        phases:
            install:
                commands:
                    - echo Installing Dependency...
                    - node -v
                    - nvm install 12.22.0
                    - node -v
                    - npm install -g next
                    - npm install -g typescript
                    - npm install
            pre_build:
                commands:
            during_build:
                commands:
                    - echo Durring Build...
                    - npm run build
                    # - chmod +x serverless_deploy_dev.sh
                    # - serverless_deploy_dev.sh
